name: Deploy Web Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy

env:
  TF_CLOUD_ORGANIZATION: "david-kamau-org"
  TF_WORKSPACE: "web-server-prod"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './David-Kamau-Builds/Work-flow/application/package-lock.json'
    - run: npm ci
      working-directory: ./David-Kamau-Builds/Work-flow/application
    - run: npm test
      working-directory: ./David-Kamau-Builds/Work-flow/application

  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - run: terraform init
      working-directory: ./David-Kamau-Builds/Work-flow/terraform
    - run: terraform validate
      working-directory: ./David-Kamau-Builds/Work-flow/terraform
    - run: terraform plan
      working-directory: ./David-Kamau-Builds/Work-flow/terraform

  deploy:
    needs: [test, terraform]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - run: terraform init
      working-directory: ./David-Kamau-Builds/Work-flow/terraform
    - run: terraform apply -auto-approve
      working-directory: ./David-Kamau-Builds/Work-flow/terraform

  manual-action:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - run: terraform init
      working-directory: ./David-Kamau-Builds/Work-flow/terraform
    - run: terraform plan
      working-directory: ./David-Kamau-Builds/Work-flow/terraform
      if: github.event.inputs.action == 'plan'
    - run: terraform apply -auto-approve
      working-directory: ./David-Kamau-Builds/Work-flow/terraform
      if: github.event.inputs.action == 'apply'
    - run: terraform destroy -auto-approve
      working-directory: ./David-Kamau-Builds/Work-flow/terraform
      if: github.event.inputs.action == 'destroy'