name: Terraform Validation

on:
  pull_request:
    branches:
      - "week*"
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  terraform-validation:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Initialize Results
        run: |
          echo "FILE_STRUCTURE_RESULTS=" >> $GITHUB_ENV
          echo "SECURITY_RESULTS=" >> $GITHUB_ENV
          echo "FORMAT_RESULTS=" >> $GITHUB_ENV
          echo "VALIDATION_RESULTS=" >> $GITHUB_ENV
          echo "HAS_ISSUES=false" >> $GITHUB_ENV

      - name: Check file structure
        id: file_structure
        continue-on-error: true
        run: |
          FILES_CHECKED=0
          INVALID_FILES=0

          for tf_file in $(find . -name "*.tf" -type f); do
            ((FILES_CHECKED++))
            if [[ ! $tf_file =~ /Day[0-9]+/Submissions/[^/]+/.*\.tf$ ]]; then
              ((INVALID_FILES++))
              echo "HAS_ISSUES=true" >> $GITHUB_ENV
              echo "FILE_STRUCTURE_RESULTS<<EOF" >> $GITHUB_ENV
              echo "### ❌ File Structure Check Failed" >> $GITHUB_ENV
              echo "- File: \`$tf_file\`" >> $GITHUB_ENV
              echo "- Required format: \`Day<number>/Submissions/<username>/*.tf\`" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            fi
          done

          if [ $INVALID_FILES -eq 0 ]; then
            echo "FILE_STRUCTURE_RESULTS<<EOF" >> $GITHUB_ENV
            echo "### ✅ File Structure Check Passed" >> $GITHUB_ENV
            echo "- All $FILES_CHECKED Terraform files follow the correct structure" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

      - name: Security and Syntax Check
        id: security
        continue-on-error: true
        run: |
          SECURI
